/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiClientsRouteImport } from './routes/api/clients'
import { Route as ApiInvoicesRouteImport } from './routes/api/invoices'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiQuotationsRouteImport } from './routes/api/quotations'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as AppBusinessRouteImport } from './routes/app.business'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTermsRouteImport } from './routes/app.terms'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api/auth/reset-password'
import { Route as ApiClientsIdRouteImport } from './routes/api/clients/$id'
import { Route as ApiInvoicesIdRouteImport } from './routes/api/invoices/$id'
import { Route as ApiQuotationsIdRouteImport } from './routes/api/quotations/$id'
import { Route as AppDocsTypeIndexRouteImport } from './routes/app.docs.$type.index'
import { Route as AppDocsTypeNewRouteImport } from './routes/app.docs.$type.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsRoute = ApiClientsRouteImport.update({
  id: '/api/clients',
  path: '/api/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesRoute = ApiInvoicesRouteImport.update({
  id: '/api/invoices',
  path: '/api/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotationsRoute = ApiQuotationsRouteImport.update({
  id: '/api/quotations',
  path: '/api/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBusinessRoute = AppBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsIdRoute = ApiClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiClientsRoute,
} as any)
const ApiInvoicesIdRoute = ApiInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvoicesRoute,
} as any)
const ApiQuotationsIdRoute = ApiQuotationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiQuotationsRoute,
} as any)
const AppDocsTypeIndexRoute = AppDocsTypeIndexRouteImport.update({
  id: '/docs/$type/',
  path: '/docs/$type/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsTypeNewRoute = AppDocsTypeNewRouteImport.update({
  id: '/docs/$type/new',
  path: '/docs/$type/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/api/quotations': typeof ApiQuotationsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/app/business': typeof AppBusinessRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/products': typeof AppProductsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/terms': typeof AppTermsRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/quotations/$id': typeof ApiQuotationsIdRoute
  '/app/docs/$type/new': typeof AppDocsTypeNewRoute
  '/app/docs/$type/': typeof AppDocsTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/api/quotations': typeof ApiQuotationsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/app/business': typeof AppBusinessRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/products': typeof AppProductsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/terms': typeof AppTermsRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/quotations/$id': typeof ApiQuotationsIdRoute
  '/app/docs/$type/new': typeof AppDocsTypeNewRoute
  '/app/docs/$type': typeof AppDocsTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/clients': typeof ApiClientsRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/api/quotations': typeof ApiQuotationsRouteWithChildren
  '/api/settings': typeof ApiSettingsRoute
  '/app/business': typeof AppBusinessRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/products': typeof AppProductsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/terms': typeof AppTermsRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/clients/$id': typeof ApiClientsIdRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/quotations/$id': typeof ApiQuotationsIdRoute
  '/app/docs/$type/new': typeof AppDocsTypeNewRoute
  '/app/docs/$type/': typeof AppDocsTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/clients'
    | '/api/invoices'
    | '/api/profile'
    | '/api/quotations'
    | '/api/settings'
    | '/app/business'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/products'
    | '/app/settings'
    | '/app/terms'
    | '/api/auth/forgot-password'
    | '/api/auth/reset-password'
    | '/api/clients/$id'
    | '/api/invoices/$id'
    | '/api/quotations/$id'
    | '/app/docs/$type/new'
    | '/app/docs/$type/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/clients'
    | '/api/invoices'
    | '/api/profile'
    | '/api/quotations'
    | '/api/settings'
    | '/app/business'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/products'
    | '/app/settings'
    | '/app/terms'
    | '/api/auth/forgot-password'
    | '/api/auth/reset-password'
    | '/api/clients/$id'
    | '/api/invoices/$id'
    | '/api/quotations/$id'
    | '/app/docs/$type/new'
    | '/app/docs/$type'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/clients'
    | '/api/invoices'
    | '/api/profile'
    | '/api/quotations'
    | '/api/settings'
    | '/app/business'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/products'
    | '/app/settings'
    | '/app/terms'
    | '/api/auth/forgot-password'
    | '/api/auth/reset-password'
    | '/api/clients/$id'
    | '/api/invoices/$id'
    | '/api/quotations/$id'
    | '/app/docs/$type/new'
    | '/app/docs/$type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiClientsRoute: typeof ApiClientsRouteWithChildren
  ApiInvoicesRoute: typeof ApiInvoicesRouteWithChildren
  ApiProfileRoute: typeof ApiProfileRoute
  ApiQuotationsRoute: typeof ApiQuotationsRouteWithChildren
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients': {
      id: '/api/clients'
      path: '/api/clients'
      fullPath: '/api/clients'
      preLoaderRoute: typeof ApiClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices': {
      id: '/api/invoices'
      path: '/api/invoices'
      fullPath: '/api/invoices'
      preLoaderRoute: typeof ApiInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotations': {
      id: '/api/quotations'
      path: '/api/quotations'
      fullPath: '/api/quotations'
      preLoaderRoute: typeof ApiQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/business': {
      id: '/app/business'
      path: '/business'
      fullPath: '/app/business'
      preLoaderRoute: typeof AppBusinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/terms': {
      id: '/app/terms'
      path: '/terms'
      fullPath: '/app/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients/$id': {
      id: '/api/clients/$id'
      path: '/$id'
      fullPath: '/api/clients/$id'
      preLoaderRoute: typeof ApiClientsIdRouteImport
      parentRoute: typeof ApiClientsRoute
    }
    '/api/invoices/$id': {
      id: '/api/invoices/$id'
      path: '/$id'
      fullPath: '/api/invoices/$id'
      preLoaderRoute: typeof ApiInvoicesIdRouteImport
      parentRoute: typeof ApiInvoicesRoute
    }
    '/api/quotations/$id': {
      id: '/api/quotations/$id'
      path: '/$id'
      fullPath: '/api/quotations/$id'
      preLoaderRoute: typeof ApiQuotationsIdRouteImport
      parentRoute: typeof ApiQuotationsRoute
    }
    '/app/docs/$type/': {
      id: '/app/docs/$type/'
      path: '/docs/$type'
      fullPath: '/app/docs/$type/'
      preLoaderRoute: typeof AppDocsTypeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs/$type/new': {
      id: '/app/docs/$type/new'
      path: '/docs/$type/new'
      fullPath: '/app/docs/$type/new'
      preLoaderRoute: typeof AppDocsTypeNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBusinessRoute: typeof AppBusinessRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProductsRoute: typeof AppProductsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTermsRoute: typeof AppTermsRoute
  AppDocsTypeNewRoute: typeof AppDocsTypeNewRoute
  AppDocsTypeIndexRoute: typeof AppDocsTypeIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBusinessRoute: AppBusinessRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProductsRoute: AppProductsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTermsRoute: AppTermsRoute,
  AppDocsTypeNewRoute: AppDocsTypeNewRoute,
  AppDocsTypeIndexRoute: AppDocsTypeIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiClientsRouteChildren {
  ApiClientsIdRoute: typeof ApiClientsIdRoute
}

const ApiClientsRouteChildren: ApiClientsRouteChildren = {
  ApiClientsIdRoute: ApiClientsIdRoute,
}

const ApiClientsRouteWithChildren = ApiClientsRoute._addFileChildren(
  ApiClientsRouteChildren,
)

interface ApiInvoicesRouteChildren {
  ApiInvoicesIdRoute: typeof ApiInvoicesIdRoute
}

const ApiInvoicesRouteChildren: ApiInvoicesRouteChildren = {
  ApiInvoicesIdRoute: ApiInvoicesIdRoute,
}

const ApiInvoicesRouteWithChildren = ApiInvoicesRoute._addFileChildren(
  ApiInvoicesRouteChildren,
)

interface ApiQuotationsRouteChildren {
  ApiQuotationsIdRoute: typeof ApiQuotationsIdRoute
}

const ApiQuotationsRouteChildren: ApiQuotationsRouteChildren = {
  ApiQuotationsIdRoute: ApiQuotationsIdRoute,
}

const ApiQuotationsRouteWithChildren = ApiQuotationsRoute._addFileChildren(
  ApiQuotationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiClientsRoute: ApiClientsRouteWithChildren,
  ApiInvoicesRoute: ApiInvoicesRouteWithChildren,
  ApiProfileRoute: ApiProfileRoute,
  ApiQuotationsRoute: ApiQuotationsRouteWithChildren,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
